Import('env')

slxargs_sources = Split("""
	rcdummy.cpp
	slx.cpp""")

slxargs_headers = Split("""
	slx.h""")

slxargs_install_headers = Split("""
	slx.h""")

slxargsenv = env.Copy()

# Set any platform specific options for this target
slxargsenv.UseTargetOptions('slxargs')

slxargs = slxargsenv.Library('slxargs', slxargs_sources)
slxargsenv.Install('$STATICLIBDIR', slxargs)
slxargsenv.Install('$INCLUDEDIR', slxargs_install_headers)

env.Distribute('shadercompiler/slxargs', slxargs_sources)
env.Distribute('shadercompiler/slxargs', slxargs_headers)
env.Distribute('shadercompiler/slxargs', 'SConscript')

