Import('env')
aqsis_sources = Split("""
	aqsis.cpp""")

aqsisenv = env.Copy();

aqsisenv.AppendUnique(LINKFLAGS = '$aqsis_exe_linkflags')

aqsis = aqsisenv.Program('aqsis', aqsis_sources, LIBS=['argparse', 'aqsis'], LIBPATH=['$LIBDIR', '$BINDIR'])
aqsisenv.Install('$BINDIR', aqsis)
