Import('env')
aqsis_sources = Split("""
	aqsis.cpp""")

aqsisenv = env.Copy();

aqsisenv.AppendUnique(LINKFLAGS = '$aqsis_exe_linkflags')

# Set any platform specific options for this target
aqsisenv.UseTargetOptions('aqsis')

aqsis = aqsisenv.Program('aqsis', aqsis_sources, LIBS=['argparse', 'aqsis'], LIBPATH=['$LIBDIR', '$BINDIR'])
aqsisenv.Install('$BINDIR', aqsis)

env.Distribute('aqsis', aqsis_sources)
env.Distribute('aqsis', 'Makefile.am')
env.Distribute('aqsis', 'SConscript')

