Import('env')
Import('pixelsave')
bmp2tif_sources=Split("""
	bmp2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('bmp2tif')

bmp2tif = env.SharedLibrary('bmp2tif', bmp2tif_sources + pixelsave, LIBS=['$tiff_lib', '$z_lib', 'jpg2tif'])
env.Install('$BINDIR', bmp2tif)
