Import('env')
bmp2tifenv = env.Copy()
bmp2tif_sources=Split("""
	bmp2tif.c""")

# Set any platform specific options for this target
bmp2tifenv.UseTargetOptions('plugin')
bmp2tifenv.UseTargetOptions('texture_plugin')
bmp2tifenv.UseTargetOptions('bmp2tif')

bmp2tif = bmp2tifenv.SharedLibrary('bmp2tif', bmp2tif_sources, LIBS=['$tiff_lib', '$z_lib', 'jpg2tif', 'common'])
bmp2tifenv.Install('$BINDIR', bmp2tif)

env.Distribute('texturing/plugins/bmp2tif', bmp2tif_sources)
env.Distribute('texturing/plugins/bmp2tif', 'SConscript')
