Import('env')

api_xml = Split("""
	api.xml""")

api_xsl = Split("""
	apiheader.xsl		apicache.xsl		apivalidate.xsl""")	


apienv = env.Copy()

apienv.UseTargetOptions('api')

apienv.Replace(APIXML = apienv.File('api.xml'))
cachegen = apienv.Command('ri_cache.inl', 'apicache.xsl', ['$XSLTPROC -o $TARGET $SOURCE $APIXML'])
headergen = apienv.Command('ri.inl', 'apiheader.xsl', ['$XSLTPROC -o $TARGET $SOURCE $APIXML'])
validategen = apienv.Command('ri_validate.inl', 'apivalidate.xsl', ['$XSLTPROC -o $TARGET $SOURCE $APIXML'])

apienv.Depends(cachegen, '$APIXML')
apienv.Depends(headergen, '$APIXML')
apienv.Depends(validategen, '$APIXML')

Export('cachegen validategen headergen')

env.Distribute('rib/api', api_xml)
env.Distribute('rib/api', api_xsl)
env.Distribute('rib/api', 'SConscript')
