Import('env', 'embedManifest')
teqserenv = env.Copy()
teqser_sources = Split("""
	teqser.cpp""")

teqserenv.AppendUnique(LIBS = ['argparse', 'shadervm', 'aqsis', 'aqsistypes'])

# Set any platform specific options for this target
teqserenv.UseTargetOptions('teqser')

teqser = teqserenv.Program('teqser', teqser_sources)

embedManifest(env, teqserenv, teqser, 'EXE')

teqserenv.Install('$BINDIR', teqser)

env.Distribute(teqser_sources)
env.Distribute("SConscript")

