Import('env')
teqserenv = env.Copy()
teqser_sources = Split("""
	teqser.cpp""")

teqserenv.AppendUnique(LIBS = ['argparse', 'aqsis'])

# Set any platform specific options for this target
teqserenv.UseTargetOptions('teqser')

teqser = teqserenv.Program('teqser', teqser_sources)
teqserenv.Install('$BINDIR', teqser)

env.Distribute('texturing/teqser', teqser_sources)
env.Distribute('texturing/teqser', "SConscript")

