Import('env')

env.Distribute('aqsistypes/posix', 'aqsis_compiler.h')
env.Distribute('aqsistypes/posix', 'file_system.cpp')
env.Distribute('aqsistypes/posix', 'SConscript')

platform_sources = Split ("""
                posix/file_system.cpp
                """)
Export('platform_sources')

