Option "display" "string file" ["${display_DISPLAYLIB}"]
Option "display" "string framebuffer" ["${piqsl_DISPLAYLIB}"]
Option "display" "string zfile" ["${display_DISPLAYLIB}"]
Option "display" "string zframebuffer" ["${piqsl_DISPLAYLIB}"]
Option "display" "string shadow" ["${display_DISPLAYLIB}"]
Option "display" "string tiff" ["${display_DISPLAYLIB}"]
Option "display" "string xpm" ["${d_xpm_DISPLAYLIB}"]
Option "display" "string exr" ["${d_exr_DISPLAYLIB}"]
Option "display" "string bmp" ["${d_bmp_DISPLAYLIB}"]
Option "display" "string debugdd" ["debugdd"]
Option "display" "string piqsl" ["${piqsl_DISPLAYLIB}"]

Option "defaultsearchpath" "string shader" ["${DEFAULT_SHADERPATH}"]
Option "defaultsearchpath" "string archive" ["${DEFAULT_ARCHIVEPATH}"]
Option "defaultsearchpath" "string texture" ["${DEFAULT_TEXTUREPATH}"]
Option "defaultsearchpath" "string display" ["${DEFAULT_DISPLAYPATH}"]
Option "defaultsearchpath" "string procedural" ["${DEFAULT_PROCEDURALPATH}"]
Option "defaultsearchpath" "string resource" ["${DEFAULT_RESOURCEPATH}"]

Option "searchpath" "string shader" [".:@:${SHADERPATH}"]
Option "searchpath" "string archive" [".:@:${ARCHIVEPATH}"]
Option "searchpath" "string texture" [".:@:${TEXTUREPATH}"]
Option "searchpath" "string display" [".:@:${DISPLAYPATH}"]
Option "searchpath" "string procedural" [".:@:${PROCEDURALPATH}"]
Option "searchpath" "string resource" [".:@:${RESOURCEPATH}"]
