Option "display" "string file" ["${display_DISPLAYLIB}"]
Option "display" "string framebuffer" ["${display_DISPLAYLIB}"]
Option "display" "string zfile" ["${display_DISPLAYLIB}"]
Option "display" "string zframebuffer" ["${display_DISPLAYLIB}"]
Option "display" "string shadow" ["${display_DISPLAYLIB}"]
Option "display" "string tiff" ["${display_DISPLAYLIB}"]
Option "display" "string xpm" ["${d_xpm_DISPLAYLIB}"]
Option "display" "string exr" ["${d_exr_DISPLAYLIB}"]
Option "display" "string bmp" ["${d_bmp_DISPLAYLIB}"]
Option "display" "string debugdd" ["debugdd"]
Option "display" "string piqsl" ["${piqsl_DISPLAYLIB}"]

Option "defaultsearchpath" "string display" ["${DISPLAYPATH}"]
Option "defaultsearchpath" "string shader" ["${SHADERPATH}"]

Option "searchpath" "string display" ["@:."]
Option "searchpath" "string shader" ["@:."]
