
Win32


Requirements:
	
	Tools:

		MSVC++ 6.0
		flex/bison		(http://unxutils.sourceforge.net)
			Note that the flex/bison that comes with Cygwin, if you have that installed, will do just as well.
			Make sure bison and flex are available in the executables directory from MSDev Tools/Options settings.
			To build the files generated by these tools you will need a standard header called unistd.h. This is a 
			standard part of Posix installations, but not available under windows. It does not need to contain anything, 
			so just creating an empty file in the standard headers directory will suffice.



	Libraries:

		libtiff		3.5.5 or later	(http://www.libtiff.org)
					Load the file libtiff\libtiff.def into you text editor and add the lines
						TIFFCreateDirectory
						TIFFDefaultStripSize
					From within the libtiff directory type
						nmake -f makefile.vc libtiff.dll
					Add libtiff to your include paths under tools/options.
					Add libtiff to your library paths under tools/options.
		libjpeg		6b or later	(http://sourceforge.net/projects/gnuwin32/)
					From within the libtiff directory type
						nmake -f makefile.vc
					Add libjpeg/src to your include paths under tools/options.
					Add libjpeg/src to your library paths under tools/options.
		zlib		1.1.3 or later	(http://www.info-zip.org/pub/infozip/zlib/)
					From the install directory type
						nmake -f Makefile.nt
					Add the install directory to your include paths under tools/options.
					Add the install directory to your library paths under tools/options.
		libargparse	Available from the Aqsis CVS repository, under the root, checkout the project libargparse.
					This will need to be built with MSVC++, and the libary directories will need to be updated
					under tools/options.


	Load the Renderer.dsw workspace from the Aqsis/Renderer directory, select the All project and build all.
