Import('env')
slppenv = env.Copy()
slppenv.AppendUnique(CPPDEFINES=['SLPP_LIBRARY'])
slpp_sources = Split("""
	PP1.C
	PP2.C
	PP3.C
	PP4.C
	PP5.C
	PP6.C
	PP7.C
	PP8.C""")
slpplib = slppenv.Library('slpp', slpp_sources)
slppenv.Install('$LIBDIR', slpplib)
# Note: Need to work out how to do an executable build of slpp as well at some point.
# There are some issues with duplicate object files.
