Import('env')
slppenv = env.Copy()
slppenv.AppendUnique(CPPDEFINES=['SLPP_LIBRARY'])
slpp_sources = Split("""
	pp1.c
	pp2.c
	pp3.c
	pp4.c
	pp5.c
	pp6.c
	pp7.c
	pp8.c""")
slpplib = slppenv.Library('slpp', slpp_sources)
slppenv.Install('$LIBDIR', slpplib)
# Note: Need to work out how to do an executable build of slpp as well at some point.
# There are some issues with duplicate object files.
