Import('env')
slxargs_sources = Split("""
	rcdummy.cpp
	slx.cpp""")

# Set any platform specific options for this target
env.UseTargetOptions('slxargs')

slxargs = env.Library('slxargs', slxargs_sources)
env.Install('$LIBDIR', slxargs)
