@ECHO OFF
cribber bucket_test.rib
cribber coordsys_test.rib
cribber disp_test.rib
cribber eyeplanetest.rib
cribber mod_st2_test.rib
cribber mod_st_test.rib
cribber orient_test.rib
cribber periodic_test.rib
cribber persptest.rib
cribber shadtest.rib
cribber space_test.rib
cribber std_st_test.rib
cribber tmap_test.rib
cribber uv_test.rib
cribber autoshadows.rib
cribber colpervertex_test.rib
cribber env_test.rib
