Import('env')

# Temporary fix, because globbing does not work with scons 0.96.92
# shaders = env.Glob(env, '*.sl')
# headers = env.Glob(env, '*.h')

shader_sources = Split("""
	shadowspot.sl
	""")
header_sources = Split("""
	""")

for shader in shader_sources:
	compiled_shader = env.Shader(shader)
	env.Install('$CONTENTDIR/shaders/light', shader)
	env.Install('$CONTENTDIR/shaders/light', compiled_shader)

env.Install('$CONTENTDIR/shaders/light', header_sources)

env.Distribute('content/shaders/light', shader_sources)
env.Distribute('content/shaders/light', header_sources)
env.Distribute('content/shaders/light', 'SConscript')

