Import('env')
Import('pixelsave')
pcx2tif_sources=Split("""
	pcx2tif.c""")
pcx2tif = env.SharedLibrary('pcx2tif', pcx2tif_sources + pixelsave, LIBS=['libtiff', 'libz'], LIBPATH=['$TPLIBS'])
env.Install('$BINDIR', pcx2tif)
