Import('env')
Import('pixelsave')
pcx2tif_sources=Split("""
	pcx2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('pcx2tif')

pcx2tif = env.SharedLibrary('pcx2tif', pcx2tif_sources + pixelsave, LIBS=['$tiff_lib', '$z_lib'])

env.Install('$BINDIR', pcx2tif)
