Import('env')
rib2_sources = Split("""
	bdec.cpp
	librib.cpp
	scanner.cpp
	parser.cpp""")
env.CXXFile(target='parser.cpp', source='parser.yy')
env.SideEffect('parser.cpp.h', 'parser.cpp')
env.CXXFile(target='scanner.cpp', source='scanner.ll')
rib2 = env.Library('rib2', rib2_sources)
env.Install('$LIBDIR', rib2)
