Import('env')
png2tifenv = env.Copy()
png2tif_sources=Split("""
	png2tif.c""")

# Set any platform specific options for this target
png2tifenv.UseTargetOptions('plugin')
png2tifenv.UseTargetOptions('texture_plugin')
png2tifenv.UseTargetOptions('png2tif')

png2tif = png2tifenv.SharedLibrary('png2tif', png2tif_sources, LIBS=['$tiff_lib', '$z_lib', 'ppm2tif', 'common'])
png2tifenv.Install('$BINDIR', png2tif)

env.Distribute('texturing/plugins/png2tif', png2tif_sources)
env.Distribute('texturing/plugins/png2tif', 'SConscript')
