Import('env', 'embedManifest')
png2tifenv = env.Copy()
png2tif_sources=Split("""
	png2tif.c""")

# Set any platform specific options for this target
png2tifenv.UseTargetOptions('plugin')
png2tifenv.UseTargetOptions('texture_plugin')
png2tifenv.UseTargetOptions('png2tif')

Import('common_objs')

png2tif = png2tifenv.SharedLibrary('png2tif', [png2tif_sources, common_objs], LIBS=['$tiff_lib', '$z_lib', 'ppm2tif'])

embedManifest(env, png2tifenv, png2tif, 'DLL')

png2tifenv.Install('$PLUGINDIR', png2tif)

env.Distribute(png2tif_sources)
env.Distribute('SConscript')
