Import('env')
png2tif_sources=Split("""
	png2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('png2tif')

png2tif = env.SharedLibrary('png2tif', png2tif_sources, LIBS=['$tiff_lib', '$z_lib', 'ppm2tif', 'common'])
env.Install('$BINDIR', png2tif)

env.Distribute('texturing/plugins/png2tif', png2tif_sources)
env.Distribute('texturing/plugins/png2tif', 'SConscript')
