Import('env')
Import('pixelsave')
ppm2tif_sources=Split("""
	ppm2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('ppm2tif')

ppm2tif = env.SharedLibrary('ppm2tif', ppm2tif_sources + pixelsave, LIBS=['$tiff_lib', '$z_lib'])

env.Install('$BINDIR', ppm2tif)
