import os.path

Import('env')

env.AppendUnique(CCFLAGS=['-Wall','-g', '-O2'])
env.AppendUnique(CPPPATH = [env.Dir('#/aqsistypes/posix')])
env.AppendUnique(CPPDEFINES=[('PLUGINS', '1')])

if not env['debug']:
	env.AppendUnique(CPPDEFINES=[('NDEBUG', '1')])

# Point at the boost headers.
# todo: need to find a way of determining this location automatically
env.Replace(boost_include_path = ['/usr/include/boost'])

# Find out where the TIFF headers are, look in common places.
tiffiofile = env.FindFile('tiffio.h', ['$tiff_include_path', '/usr/include'])
if tiffiofile != None:
	env.Replace(tiff_include_path = os.path.dirname(tiffiofile.abspath))

# Find out where the TIFF libraries are, look in common places for Fink and DarwinPorts.
tifflibfile = env.FindFile('libtiff.a', ['$tiff_lib_path', '/usr/lib'])
if tifflibfile != None:
	env.Replace(tiff_lib_path = os.path.dirname(tifflibfile.abspath))
env.Replace(tiff_lib = 'tiff')

# Find out where the JPEG headers are, look in common places for Fink and DarwinPorts.
jpegiofile = env.FindFile('jpeglib.h', ['$jpeg_include_path', '/usr/include', '/usr/include'])
if jpegiofile != None:
	env.Replace(jpeg_include_path = os.path.dirname(jpegiofile.abspath))

# Find out where the JPEG libraries are, look in common places for Fink and DarwinPorts.
jpeglibfile = env.FindFile('libjpeg.a', ['$jpeg_lib_path', '/usr/lib', '/usr/lib'])
if jpeglibfile != None:
	env.Replace(jpeg_lib_path = os.path.dirname(jpeglibfile.abspath))
env.Replace(jpeg_lib = 'jpeg')

# Find out where the zlib headers are, look in common places for Fink and DarwinPorts.
zlibiofile = env.FindFile('zlib.h', ['$zlib_include_path', '/usr/include', '/usr/include'])
if zlibiofile != None:
	env.Replace(zlib_include_path = os.path.dirname(zlibiofile.abspath))

# Find out where the zlib libraries are, look in common places for Fink and DarwinPorts.
zliblibfile = env.FindFile('libz.a', ['$zlib_lib_path', '/usr/lib', '/usr/lib'])
if zliblibfile != None:
	env.Replace(zlib_lib_path = os.path.dirname(zliblibfile.abspath))
env.Replace(z_lib = 'z')

# Find out where the OpenEXR libraries are, look in common places 
exriofile = env.FindFile('half.h', ['$exr_include_path', '/usr/local/include/OpenEXR', '/opt/local/include/OpenEXR', '/usr/include/OpenEXR'])
if exriofile != None:
	env.Replace(exr_include_path = os.path.dirname(exriofile.abspath))

exrlibfile = env.FindFile('libIlmImf.a', ['$exr_lib_path', '/usr/local/lib', '/opt/local/lib', '/usr/lib'])
if exrlibfile != None:
	env.Replace(exr_lib_path = os.path.dirname(exrlibfile.abspath))
env.Replace(exr_lib = 'Iex')
env.Replace(exr2tif_libs = ['IlmImf', 'Half', 'Iex', 'Imath'])

# Find out where the fltk headers are, look in common places for Fink and DarwinPorts.
fltkfile = env.FindFile('FL/fl.h', ['$fltk_include_path', '/usr/include'])
if fltkfile != None:
	env.Replace(fltk_include_path = os.path.split(os.path.dirname(fltkfile.abspath))[0])

# Find out where the fltk libraries are, look in common places for Fink and DarwinPorts.
fltklibfile = env.FindFile('libfltk.a', ['$fltk_lib_path', '/usr/lib'])
if fltklibfile != None:
	env.Replace(fltk_lib_path = os.path.dirname(fltklibfile.abspath))
env.Replace(fltk_lib = 'fltk')


# Setup the xsltproc program location
env.Replace(XSLTPROC = 'xsltproc')

env.Replace(YACC = '${bison}')
env.Replace(LEX = '${flex}')
env.Replace(YACCFLAGS = '--no-lines -d')

# Make sure any relative paths are relative to the _top_ of the scons directory structure
for path in ('$destdir', '$libdir', '$libexecdir', '$sysconfdir'):
	if env.subst(path) != '' and not (env.subst(path)[0] in ['/','#']):
		env.Replace( **{path[1:]: '#' + env.subst(path)} )
# Update the install paths; use env.Dir, since otherwise scons (v-0.96.1) crashes with an obscure bug.
env.Replace(LIBDIR = env.Dir('$libdir'))
env.Replace(RENDERENGINEDIR = env.Dir('$LIBDIR'))
env.Replace(DISPLAYSDIR = env.Dir('$libexecdir'))
env.Replace(PLUGINDIR = env.Dir('$LIBDIR/aqsis'))
env.Replace(STATICLIBDIR = env.Dir('$LIBDIR/aqsis'))
env.Replace(SHADERDIR = env.Dir('$install_prefix/share/aqsis/shaders'))
env.Replace(SYSCONFDIR = env.Dir('$sysconfdir'))

if env.subst('$destdir') != '':
	if 'dist' in BUILD_TARGETS or 'dist_zip' in BUILD_TARGETS or 'dist_tar' in BUILD_TARGETS:
		import sys
		sys.stderr.write('***\n')
		sys.stderr.write('*** WARNING: $destdir!="" and the "dist*" targets are incompatible.  Ignoring $destdir.\n')
		sys.stderr.write('***\n')
	else:
		env.Replace(DESTDIR = env.Dir('$destdir'))
		# Replace the scons Install() function with a wrapper which modifies the
		# install path to be prefixed by $DESTDIR
		env.SconsInternalInstallFunc = env.Install
		def InstallWithDestDir(dir, source):
			return env.SconsInternalInstallFunc('$DESTDIR'+env.Dir(dir).abspath, source)
		env.Install = InstallWithDestDir
		# Update the install directories to reflect the changes.
		env.Replace(INSTALL_DIRS = [ '$DESTDIR' + env.Dir(dir).abspath for dir in env['INSTALL_DIRS'] ] )

# These absolute paths are necessary because there's no good general way of
# getting a running program's install path on unix-like systems.
env.AppendUnique(CPPDEFINES=[('DEFAULT_RC_PATH', '\\"' + env.Dir('$SYSCONFDIR').abspath + '\\"')])
env.AppendUnique(CPPDEFINES=[('DEFAULT_SHADER_PATH', '\\"' + env.Dir('$SHADERDIR').abspath + '\\"')])

env.Replace(slparse_ccflags = ['-O0'])
env.Replace(aqsis_libs = ['dl'])
env.Replace(aqsltell_libs = ['dl'])
env.Replace(teqser_libs = ['dl'])

