Import('env')
raytrace_sources = Split("""
	raytrace.cpp""")

raytrace_headers = Split("""
	raytrace.h""")

raytraceenv = env.Copy()

# Set any platform specific options for this target
raytraceenv.UseTargetOptions('raytrace')

raytrace_objs = [raytraceenv.SharedObject(file) for file in raytrace_sources]

Export('raytrace_objs')

env.Distribute('renderer/raytrace', raytrace_sources)
env.Distribute('renderer/raytrace', raytrace_headers)
env.Distribute('renderer/raytrace', 'SConscript')

