Import('env')
shaderexecenv_sources = Split("""
	shaderexecenv.cpp
	shadeops.cpp""")

# Set any platform specific options for this target
env.UseTargetOptions('shaderexecenv')

shaderexecenv = env.Library('shaderexecenv', shaderexecenv_sources)
env.Install('$LIBDIR', shaderexecenv)
