Import('env')
slparse_sources = Split("""
	funcdef.cpp
	libslparse.cpp
	optimise.cpp
	parsenode.cpp
	parser.cpp
	scanner.cpp
	typecheck.cpp
	vardef.cpp""")
slparseenv = env.Copy()

# Need to disable optimisation on gcc platforms as it takes too much memory.
if 'darwin' == slparseenv['PLATFORM']:
	slparseenv.AppendUnique(CCFLAGS=['-O0'])

slparseenv.CXXFile(target='parser.cpp', source='parser.yy')
slparseenv.CXXFile(target='scanner.cpp', source='scanner.ll')
slparse = slparseenv.Library('slparse', slparse_sources)
slparseenv.Install('$LIBDIR', slparse)
