Import('env')
slparse_sources = Split("""
	funcdef.cpp
	libslparse.cpp
	optimise.cpp
	parsenode.cpp
	parser.cpp
	scanner.cpp
	typecheck.cpp
	vardef.cpp""")
slparseenv = env.Copy()

slparseenv.UseTargetOptions('slparse')

slparseenv.CXXFile(target='parser.cpp', source='parser.yy')
slparseenv.CXXFile(target='scanner.cpp', source='scanner.ll')
slparse = slparseenv.Library('slparse', slparse_sources)
slparseenv.Install('$LIBDIR', slparse)
