Import('env')
d_xpmenv = env.Copy()
d_xpmenv.AppendUnique(CPPPATH=['#/renderer/ddmanager'])
d_xpmenv.AppendUnique(CPPDEFINES=['d_xpm_EXPORTS'])

d_xpm_sources = Split("""
	xpm.cpp
	aspXpm.cpp""")

d_xpm_headers =  Split("""
	aspXpm.h""")


d_xpmenv.AppendUnique(LIBS = ['$tiff_lib', '$z_lib'])

# Set any platform specific target options.
d_xpmenv.UseTargetOptions('d_xpm')

d_xpm = d_xpmenv.SharedLibrary('d_xpm', d_xpm_sources)
d_xpmenv.Install('$DISPLAYSDIR', d_xpm)

Return('d_xpm')

env.Distribute(d_xpm_sources)
env.Distribute(d_xpm_headers)
env.Distribute('SConscript')

