Import('env')

rib2ri_sources = env.File(Split("""
	librib2ri.cpp"""))

rib2ri_headers = Split("""
	librib2ri.h""")

rib2ri_install_headers = Split("""
	librib2ri.h""")

rib2rienv = env.Copy()
rib2rienv.AppendUnique(CPPDEFINES=['RIB_EXPORTS'])

# Set any platform specific options for this target
rib2rienv.UseTargetOptions('rib2ri')

if env.has_key('rib2ri_add_sources'):
	rib2ri_sources = rib2ri_sources + ['$rib2ri_add_sources']

env.Distribute(rib2ri_sources)
env.Distribute(rib2ri_headers)
env.Distribute('SConscript')

Export('rib2ri_sources')
