Import('env')
shaderexecenv_sources = Split("""
	shaderexecenv.cpp
	shadeops_comp.cpp
	shadeops_deriv.cpp
	shadeops_illum.cpp
	shadeops_inter.cpp
	shadeops_math.cpp
	shadeops_matrx.cpp
	shadeops_rand.cpp
	shadeops_text.cpp
	shadeops_tmap.cpp
""")

shaderexecenv_headers = Split("""
	shaderexecenv.h""")

# Set any platform specific options for this target
env.UseTargetOptions('shaderexecenv')

shaderexecenv = env.Library('shaderexecenv', shaderexecenv_sources)
env.Install('$LIBDIR', shaderexecenv)

env.Distribute('shadercompiler/shaderexecenv', shaderexecenv_sources)
env.Distribute('shadercompiler/shaderexecenv', shaderexecenv_headers)
env.Distribute('shadercompiler/shaderexecenv', 'SConscript')

