Import('env')
shaderexecenv_sources = Split("""
	shaderexecenv.cpp
	shadeops.cpp
	shadeops1.cpp
	shadeops2.cpp
	shadeops3.cpp
	shadeops4.cpp
	shadeops5.cpp
	shadeops6.cpp
	shadeops7.cpp
	shadeops8.cpp
""")

shaderexecenv_headers = Split("""
	shaderexecenv.h""")

# Set any platform specific options for this target
env.UseTargetOptions('shaderexecenv')

shaderexecenv = env.Library('shaderexecenv', shaderexecenv_sources)
env.Install('$LIBDIR', shaderexecenv)

env.Distribute('shadercompiler/shaderexecenv', shaderexecenv_sources)
env.Distribute('shadercompiler/shaderexecenv', shaderexecenv_headers)
env.Distribute('shadercompiler/shaderexecenv', 'SConscript')

