Import('env')
rib2_sources = Split("""
	bdec.cpp
	librib.cpp
	scanner.cpp
	parser.cpp""")

rib2_headers = Split("""
	bdec.h
	librib.h
	libribtypes.h
	parserstate.h""")

rib2_install_headers = Split("""
	librib.h
	parserstate.h""")

rib2env = env.Copy()

rib2env.CXXFile(target='parser.cpp', source='parser.yy')
rib2env.CXXFile(target='scanner.cpp', source='scanner.ll')

# Set any platform specific options for this target
rib2env.UseTargetOptions('rib2')

rib2 = rib2env.Library('rib2', rib2_sources)
#rib2env.Install('$STATICLIBDIR', rib2)
#rib2env.Install('$INCLUDEDIR', rib2_install_headers)

env.Distribute('rib/rib2', rib2_sources)
env.Distribute('rib/rib2', rib2_headers)
env.Distribute('rib/rib2', 'SConscript')
env.Distribute('rib/rib2', 'scanner.ll')
env.Distribute('rib/rib2', 'parser.yy')

