Import('env')
Import('pixelsave')
bake2tif_sources=Split("""
	bake2tif.c""")

bake2tif = env.SharedLibrary('bake2tif', bake2tif_sources + pixelsave, LIBS=['$tiff_lib', '$z_lib'])

env.Install('$BINDIR', bake2tif)
