Import('env version')

installer1env = env.Copy()
installer1env.Replace(NSISDEFINES = {'PRODUCT_VERSION': '%d.%d.%d' %(version.major, version.minor, version.build), 
				 'PRODUCT_FILE_NUMBER': '%d_%d_%d' %(version.major, version.minor, version.build),
				 'LIBRARY_EXTENSION': env['LIBSUFFIX']})
installer1 = installer1env.Installer('setup')
env.Depends('installer1', 'release')
installer1env.Alias('win_installer', installer1)

env.Distribute('distribution/win/nsis/', 'SConscript')
env.Distribute('distribution/win/nsis/', 'setup.nsi')
env.Distribute('distribution/win/nsis/', 'page_tasks.ini')
