INCLUDE_DIRECTORIES(${AQSISTYPES_SOURCE_DIR})
# TODO: choose the right subdirectory
IF(UNIX OR APPLE)
	INCLUDE_DIRECTORIES(${AQSISTYPES_SOURCE_DIR}/posix)
ELSE(UNIX OR APPLE)
	INCLUDE_DIRECTORIES(${AQSISTYPES_SOURCE_DIR}/win32)
ENDIF(UNIX OR APPLE)

