INCLUDE_DIRECTORIES(${AQSISTYPES_SOURCE_DIR})
INCLUDE_DIRECTORIES(${AQSISTYPES_BINARY_DIR})  # for aqsis_config.h

IF(UNIX OR APPLE)
	INCLUDE_DIRECTORIES(${AQSISTYPES_SOURCE_DIR}/posix)
ELSE(UNIX OR APPLE)
	INCLUDE_DIRECTORIES(${AQSISTYPES_SOURCE_DIR}/win32)
ENDIF(UNIX OR APPLE)

