Import('env')
commonenv = env.Copy()

common_sources = Split("""
	pixelsave.c""")

common_headers = Split("""
	pixelsave.h""")

# Set any platform specific options for this target
commonenv.UseTargetOptions('common')

#common = commonenv.Library('common', common_sources)

common_objs = [commonenv.SharedObject(file) for file in common_sources]

Export('common_objs')

env.Distribute('texturing/plugins/common', common_sources)
env.Distribute('texturing/plugins/common', common_headers)
env.Distribute('texturing/plugins/common', 'SConscript')

