Import('env')
commonenv = env.Copy()

common_sources = Split("""
	pixelsave.c""")

common_headers = Split("""
	pixelsave.h""")

# Set any platform specific options for this target
commonenv.UseTargetOptions('common')

common = commonenv.Library('common', common_sources)

env.Distribute('texturing/plugins/common', common_sources)
env.Distribute('texturing/plugins/common', common_headers)
env.Distribute('texturing/plugins/common', 'SConscript')

