Import('env')
Import('pixelsave')
tga2tif_sources=Split("""
	tga2tif.c""")
tga2tif = env.SharedLibrary('tga2tif', tga2tif_sources + pixelsave, LIBS=['libtiff', 'libz', 'jpg2tif'], LIBPATH=['$BINDIR', '$TPLIBS'])
env.Install('$BINDIR', tga2tif)
