Import('env')
displayenv = env.Copy()
displayenv.AppendUnique(CPPPATH=['#/renderer/ddmanager'])
displayenv.AppendUnique(CPPDEFINES=['DISPLAY_EXPORTS'])

display_sources = Split("""
	display.cpp
	displayhelpers.c""")

display_headers =  Split("""
	display.h""")


displayenv.AppendUnique(LIBS = ['aqsistypes', '$tiff_lib', '$z_lib', '$fltk_lib'])
displayenv.AppendUnique(CPPPATH=['$tiff_include_path', '$zlib_include_path', '$fltk_include_path'])

# Set any platform specific target options.
displayenv.UseTargetOptions('display')

display = displayenv.SharedLibrary('display', display_sources)

if env['MSVS_VERSION'] == '8.0':
	displayenv.AddPostAction(display, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')
	
displayenv.Install('$DISPLAYSDIR', display)

Return('display')

env.Distribute(display_sources)
env.Distribute(display_headers)
env.Distribute('SConscript')

