Import('env')

shadervm_sources = Split("""
	dsoshadeops.cpp
	shaderstack.cpp
	shadervariable.cpp
	shadervm.cpp
	shadervm1.cpp
	shadervm2.cpp""")

shadervm_headers = Split("""
	dsoshadeops.h
	shaderstack.h
	shadervariable.h
	shadervm.h""")

# Set any platform specific options for this target
env.UseTargetOptions('shadervm')

shadervm = env.Library('shadervm', shadervm_sources)
env.Install('$LIBDIR', shadervm)

env.Distribute('shadercompiler/shadervm', shadervm_sources)
env.Distribute('shadercompiler/shadervm', shadervm_headers)
env.Distribute('shadercompiler/shadervm', 'SConscript')

