Import('env')

argparse_sources = Split("""
	argparse.cpp""")

argparse_headers = Split("""
	argparse.h""")

argparse_install_headers = Split("""
	argparse.h""")

argparseenv = env.Copy()

# Set any platform specific options for this target
argparseenv.UseTargetOptions('argparse')

argparse = argparseenv.Library('argparse', argparse_sources)
argparseenv.Install('$STATICLIBDIR', argparse)
argparseenv.Install('$INCLUDEDIR', argparse_install_headers)

env.Distribute('argparse', argparse_sources)
env.Distribute('argparse', argparse_headers)
env.Distribute('argparse', 'SConscript')

