Import('env')
tga2tifenv = env.Copy()
tga2tif_sources=Split("""
	tga2tif.c""")

# Set any platform specific options for this target
tga2tifenv.UseTargetOptions('plugin')
tga2tifenv.UseTargetOptions('texture_plugin')
tga2tifenv.UseTargetOptions('tga2tif')

Import('common_objs')

tga2tif = tga2tifenv.SharedLibrary('tga2tif', [tga2tif_sources, common_objs], LIBS=['$tiff_lib', '$z_lib', 'jpg2tif'])

if env['MSVS_VERSION'] == '8.0':
	tga2tifenv.AddPostAction(tga2tif, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')

tga2tifenv.Install('$PLUGINDIR', tga2tif)

env.Distribute(tga2tif_sources)
env.Distribute('SConscript')
