Import('env')
tga2tif_sources=Split("""
	tga2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('tga2tif')

tga2tif = env.SharedLibrary('tga2tif', tga2tif_sources, LIBS=['$tiff_lib', '$z_lib', 'jpg2tif', 'common'])

env.Install('$BINDIR', tga2tif)
