Import('env')
jpg2tifenv = env.Copy()
jpg2tif_sources=Split("""
	jpg2tif.c""")

jpg2tifenv.AppendUnique(CPPPATH=['$jpeg_include_path'])

# Set any platform specific options for this target
jpg2tifenv.UseTargetOptions('plugin')
jpg2tifenv.UseTargetOptions('texture_plugin')
jpg2tifenv.UseTargetOptions('jpg2tif')

Import('common_objs')

jpg2tif = jpg2tifenv.SharedLibrary('jpg2tif', [jpg2tif_sources, common_objs], LIBS=['$tiff_lib', '$z_lib', '$jpeg_lib'])

if env['MSVS_VERSION'] == '8.0':
		jpg2tifenv.AddPostAction(jpg2tif, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')

jpg2tifenv.Install('$PLUGINDIR', jpg2tif)

env.Distribute(jpg2tif_sources)
env.Distribute('SConscript')
