Import('env')
jpg2tif_sources=Split("""
	jpg2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('jpg2tif')

jpg2tif = env.SharedLibrary('jpg2tif', jpg2tif_sources, LIBS=['common', '$tiff_lib', '$z_lib', '$jpeg_lib'])

env.Install('$BINDIR', jpg2tif)
