Import('env')

scene_data = Split("""
	vase.rib
	render.bat
	render.sh
	""")

env.Install('$CONTENTDIR/ribs/scenes/vase', scene_data)

env.Distribute('content/ribs/scenes/vase', scene_data)
env.Distribute('content/ribs/scenes/vase', 'SConscript')

