Import('env')
shadervm_sources = Split("""
	dsoshadeops.cpp
	shaderstack.cpp
	shadervariable.cpp
	shadervm.cpp
	shadervm1.cpp
	shadervm2.cpp""")
shadervm = env.Library('shadervm', shadervm_sources)
env.Install('$LIBDIR', shadervm)
