Import('env Glob')


shaders = Glob('*.sl')
headers = Glob('*.h')

for shader in shaders:
	compiled_shader = env.Shader(shader)
	env.Install('$SHADERDIR', shader)
	env.Install('$SHADERDIR', compiled_shader)

env.Distribute('shaders', shaders)
env.Distribute('shaders', headers)
env.Distribute('shaders', 'SConscript')

