Import('env')
aqsis_sources = Split("""
	aqsis.cpp""")

aqsisenv = env.Copy();

aqsisenv.AppendUnique(LIBS = ['argparse', 'aqsis'])

# Set any platform specific options for this target
aqsisenv.UseTargetOptions('aqsis')

aqsis = aqsisenv.Program('aqsis', aqsis_sources)
aqsisenv.Install('$BINDIR', aqsis)

env.Distribute('renderer/aqsis', aqsis_sources)
env.Distribute('renderer/aqsis', 'SConscript')

Return('aqsis')
