Import('env')
aqsis_sources = Split("""
	aqsis.cpp""")

aqsisenv = env.Copy();

aqsisenv.AppendUnique(LIBS = ['argparse', 'aqsistypes', 'aqsis', 'shadervm'])
aqsisenv.AppendUnique(CPPPATH=['$zlib_include_path'])

# Set any platform specific options for this target
aqsisenv.UseTargetOptions('aqsis')

aqsis = aqsisenv.Program('aqsis', aqsis_sources)

if env['MSVS_VERSION'] == '8.0':
	aqsisenv.AddPostAction(aqsis, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;1')

aqsisenv.Install('$BINDIR', aqsis)

env.Distribute(aqsis_sources)
env.Distribute('SConscript')

Return('aqsis')
