Import('env')

rib2stream_sources = Split("""
	librib2stream.cpp""")

rib2stream_headers = Split("""
	librib2stream.h""")

# Set any platform specific options for this target
env.UseTargetOptions('rib2stream')

rib2stream = env.Library('rib2stream', rib2stream_sources)
env.Install('$LIBDIR', rib2stream)

env.Distribute('librib2stream', rib2stream_sources)
env.Distribute('librib2stream', rib2stream_headers)
env.Distribute('librib2stream', 'SConscript')

