Import('env')

argparse_sources = Split("""
	argparse.cpp""")

argparse_headers = Split("""
	argparse.h""")

# Set any platform specific options for this target
env.UseTargetOptions('argparse')

argparse = env.Library('argparse', argparse_sources)
env.Install('$LIBDIR', argparse)

env.Distribute('libargparse', argparse_sources)
env.Distribute('libargparse', argparse_headers)
env.Distribute('libargparse', 'SConscript')

