Import('env')
aqsisdll_sources = Split("""
	attributes.cpp
	bound.cpp
	bucket.cpp
	condition.cpp
	converter.cpp
	csgtree.cpp
	curves.cpp
	environment.cpp
	genpoly.cpp
	graphicsstate.cpp
	imagebuffer.cpp
	imagepixel.cpp
	imagers.cpp
	inlineparse.cpp
	lath.cpp
	lights.cpp
	micropolygon.cpp
	mpdump.cpp
	nurbs.cpp
	occlusion.cpp
	options.cpp
	parameters.cpp
	patch.cpp
	points.cpp
	polygon.cpp
	procedural.cpp
	quadrics.cpp
	render.cpp
	renderer.cpp
	ri.cpp
	shaders.cpp
	shadowmap.cpp
	stats.cpp
	subdivision2.cpp
	surface.cpp
	symbols.cpp
	teapot.cpp
	texturemap.cpp
	transform.cpp
	trimcurve.cpp""")
aqsisenv = env.Copy()
aqsisenv.AppendUnique(CPPDEFINES=[('_qBUILDING', 'CORE'), ('CORE', 1)])

if 'darwin' == aqsisenv['PLATFORM']:
	aqsisenv.AppendUnique(LINKFLAGS = ['-framework', 'Carbon'])

if 'win32' == aqsisenv['PLATFORM']:
	aqsisdll_sources = aqsisdll_sources + ["libaqsis.def"]


aqsisdll = aqsisenv.SharedLibrary('aqsis', aqsisdll_sources, 
	LIBS=['ddmanager', 'raytrace', 'rib2', 'rib2ri', 'shaderexecenv', 'shadervm', 'aqsistypes', '$tiff_lib', '$z_lib'])

aqsisenv.Install('$BINDIR', aqsisdll)
