Import('env')

rib2stream_sources = Split("""
	librib2stream.cpp""")

rib2stream_headers = Split("""
	librib2stream.h""")

rib2stream_install_headers = Split("""
	librib2stream.h""")

rib2streamenv = env.Copy()

# Set any platform specific options for this target
rib2streamenv.UseTargetOptions('rib2stream')

rib2stream = rib2streamenv.Library('rib2stream', rib2stream_sources)
rib2streamenv.Install('$LIBDIR', rib2stream)
rib2streamenv.Install('$INCLUDEDIR', rib2stream_install_headers)

env.Distribute('rib/rib2stream', rib2stream_sources)
env.Distribute('rib/rib2stream', rib2stream_headers)
env.Distribute('rib/rib2stream', 'SConscript')

