Import('env')
slppenv = env.Copy()
slppenv.AppendUnique(CPPDEFINES=['SLPP_LIBRARY'])
slpp_sources = Split("""
	pp1.c
	pp2.c
	pp3.c
	pp4.c
	pp5.c
	pp6.c
	pp7.c
	pp8.c""")

slpp_headers = Split("""
	pp.h
	ppext.h""")

# Set any platform specific options for this target
slppenv.UseTargetOptions('slpplib')

slpp_objs = [slppenv.Object(file) for file in slpp_sources]

Export('slpp_objs')

# Note: Need to work out how to do an executable build of slpp as well at some point.
# There are some issues with duplicate object files.

env.Distribute('shadercompiler/slpp', slpp_sources)
env.Distribute('shadercompiler/slpp', slpp_headers)
env.Distribute('shadercompiler/slpp', 'PP.DOC')
env.Distribute('shadercompiler/slpp', 'SConscript')
