Import('env')
gif2tifenv = env.Copy()
gif2tif_sources=Split("""
	gif2tif.c""")

# Set any platform specific options for this target
gif2tifenv.UseTargetOptions('plugin')
gif2tifenv.UseTargetOptions('texture_plugin')
gif2tifenv.UseTargetOptions('gif2tif')

gif2tif = gif2tifenv.SharedLibrary('gif2tif', gif2tif_sources, LIBS=['common', '$tiff_lib', '$z_lib'])

gif2tifenv.Install('$BINDIR', gif2tif)

env.Distribute('texturing/plugins/gif2tif', gif2tif_sources)
env.Distribute('texturing/plugins/gif2tif', 'SConscript')
