Import('env')
eqshibitenv = env.Copy()
eqshibitenv.AppendUnique(CPPPATH = ['#/aqsis/aqsistypes'])
eqshibitenv.AppendUnique(LIBS = ['$tiff_lib', '$fltk_lib','#/thirdparty/tinyxml'])

eqshibit_sources = Split("""
	eqshibit.cpp""")

# Set any platform specific options for this target
eqshibitenv.UseTargetOptions('eqshibit')


eqshibit = eqshibitenv.Program('eqshibit', eqshibit_sources, LIBS=['aqsistypes','argparse','fltk','m','Xext','X11','supc++','tinyxml'], LIBPATH=['$LIBDIR','/usr/X11R6/lib'])
eqshibitenv.Install('$BINDIR', eqshibit)

env.Distribute('displays/display/eqshibit', eqshibit_sources)
env.Distribute('displays/display/eqshibit', "SConscript")

