Import('env')
codegenvm_sources = Split("""
	vmdatagather.cpp
	vmoutput.cpp
	codegenvm.cpp""")

codegenvm_headers = Split("""
	codegenvm.h
	vmdatagather.h
	vmoutput.h""")

codegenvmenv = env.Copy()

# Set any platform specific options for this target
codegenvmenv.UseTargetOptions('codegenvm')

codegenvm = codegenvmenv.Library('codegenvm', codegenvm_sources)
#codegenvmenv.Install('$STATICLIBDIR', codegenvm)

env.Distribute('shadercompiler/codegenvm', codegenvm_sources)
env.Distribute('shadercompiler/codegenvm', codegenvm_headers)
env.Distribute('shadercompiler/codegenvm', 'SConscript')

