Import('env')
pcx2tifenv = env.Copy()
pcx2tif_sources=Split("""
	pcx2tif.c""")

# Set any platform specific options for this target
pcx2tifenv.UseTargetOptions('plugin')
pcx2tifenv.UseTargetOptions('texture_plugin')
pcx2tifenv.UseTargetOptions('pcx2tif')

Import('common_objs')

pcx2tif = pcx2tifenv.SharedLibrary('pcx2tif', [pcx2tif_sources, common_objs], LIBS=['$tiff_lib', '$z_lib'])

if env['MSVS_VERSION'] == '8.0':
		pcx2tifenv.AddPostAction(pcx2tif, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')

pcx2tifenv.Install('$PLUGINDIR', pcx2tif)

env.Distribute(pcx2tif_sources)
env.Distribute('SConscript')
