Import('env')
ddmanager_sources = Split("""
	ddmanager.cpp
	debugdd.cpp""")

ddmanager_headers = Split("""
	ddmanager.h
	debugdd.h
	ndspy.h""")

ddmanagerenv = env.Copy()

# Set any platform specific options for this target
ddmanagerenv.UseTargetOptions('ddmanager')

ddmanager_objs = [ddmanagerenv.SharedObject(file) for file in ddmanager_sources]

Export('ddmanager_objs')

ddmanagerenv.Install('$INCLUDEDIR', "ndspy.h")

env.Distribute('renderer/ddmanager', ddmanager_sources)
env.Distribute('renderer/ddmanager', ddmanager_headers)
env.Distribute('renderer/ddmanager', 'SConscript')
