Import('env')

interfaces_headers = Split("""
	ilightsource.h
	iraytrace.h
	irenderer.h
	ishader.h
	ishaderdata.h
	ishaderexecenv.h
	isurface.h
	itexturemap.h
	itransform.h
	iattributes.h              ioptions.h
	iddmanager.h """)

env.Distribute(interfaces_headers)

