Import('env')

scene_data = Split("""
	grid.tif
	layered.rib
	texmap.sl
	render.bat
	""")

env.Install('$CONTENTDIR/ribs/features/layeredshaders', scene_data)

env.Distribute('content/ribs/features/layeredshaders', scene_data)
env.Distribute('content/ribs/features/layeredshaders', 'SConscript')

