Import('env')
raytrace_sources = Split("""
	raytrace.cpp""")

raytrace_headers = Split("""
	raytrace.h""")

# Set any platform specific options for this target
env.UseTargetOptions('raytrace')

raytrace = env.Library('raytrace', raytrace_sources)
env.Install('$LIBDIR', raytrace)

env.Distribute('libraytrace', raytrace_sources)
env.Distribute('libraytrace', raytrace_headers)
env.Distribute('libraytrace', 'SConscript')
env.Distribute('libraytrace', 'Makefile.am')

