Import('env')
bake2tif_sources=Split("""
	bake2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('bake2tif')

bake2tif = env.SharedLibrary('bake2tif', bake2tif_sources, LIBS=['$tiff_lib', '$z_lib', 'common'])

env.Install('$BINDIR', bake2tif)
