Import('env')

exr2tif_sources=Split("""
	exr2tif.cpp""")

if not env['no_exr']:
	exr2tifenv = env.Copy()
	exr2tifenv.AppendUnique(CPPPATH=['$exr_include_path'])

	Import('common_objs')

	exr2tifenv.Replace(LIBS = ['$tiff_lib'])

	# Set any platform specific options for this target
	exr2tifenv.UseTargetOptions('plugin')
	exr2tifenv.UseTargetOptions('texture_plugin')
	exr2tifenv.UseTargetOptions('exr2tif')

	exr2tif = exr2tifenv.SharedLibrary('exr2tif', [exr2tif_sources, common_objs])

	exr2tifenv.Install('$PLUGINDIR', exr2tif)

env.Distribute(exr2tif_sources)
env.Distribute('SConscript')
