Import('env')
exr2tifenv = env.Copy()
exr2tifenv.AppendUnique(CPPPATH=['$exr_include_path'])
exr2tif_sources=Split("""
	exr2tif.cpp""")

exr2tifenv.Replace(LIBS = ['common', '$tiff_lib'])

# Set any platform specific options for this target
exr2tifenv.UseTargetOptions('plugin')
exr2tifenv.UseTargetOptions('texture_plugin')
exr2tifenv.UseTargetOptions('exr2tif')

exr2tif = exr2tifenv.SharedLibrary('exr2tif', exr2tif_sources, LIBS=['common', '$tiff_lib', 'IlmImf', 'Half', 'Iex', 'Imath'])

exr2tifenv.Install('$BINDIR', exr2tif)
