Import('env')
ri2rib_sources = Split("""
	ascii.cpp
	binary.cpp
	context.cpp
	dictionary.cpp
	error.cpp
	inlineparse.cpp
	output.cpp
	outstream.cpp
	plstore.cpp
	ri.cpp
	tokens.cpp""")
ri2rib = env.Library('ri2rib', ri2rib_sources)
env.Install('$LIBDIR', ri2rib)
