SET(AQSIS_XCODEBUILD_SEARCHPATH)
# If on win32, and the win32libs SVN module has been located, we can
# use the one in there.
IF(APPLE)
	FIND_PROGRAM(AQSIS_XCODEBUILD_EXECUTABLE
		xcodebuild
		PATHS ${AQSIS_XCODEBUILD_SEARCHPATH}
		DOC "Location of the xcodebuild executable"
	)

	STRING(COMPARE NOTEQUAL ${AQSIS_XCODEBUILD_EXECUTABLE} "AQSIS_XCODEBUILD_EXECUTABLE-NOTFOUND" AQSIS_XCODEBUILD_EXECUTABLE_FOUND)
ENDIF(APPLE)