FIND_PROGRAM(AQSIS_XSLTPROC_EXECUTABLE
	xsltproc
	DOC "Location of the xsltproc executable"
)

STRING(COMPARE NOTEQUAL ${AQSIS_XSLTPROC_EXECUTABLE} "AQSIS_XSLTPROC_EXECUTABLE-NOTFOUND" AQSIS_XSLTPROC_EXECUTABLE_FOUND)
