SET(AQSIS_NSIS_SEARCHPATH)

IF(WIN32)
	SET(AQSIS_NSIS_SEARCHPATH "$ENV{PROGRAMFILES}/NSIS")
ENDIF(WIN32)

FIND_PROGRAM(AQSIS_NSIS_EXECUTABLE
	makensis
	PATHS ${AQSIS_NSIS_SEARCHPATH}
	DOC "Location of the NSIS executable"
)

STRING(COMPARE NOTEQUAL ${AQSIS_NSIS_EXECUTABLE} "AQSIS_NSIS_EXECUTABLE-NOTFOUND" AQSIS_NSIS_EXECUTABLE_FOUND)
