# Custom Aqsis specific version of FindTIFF
SET(AQSIS_TIFF_FOUND 0)

SET(AQSIS_TIFF_INCLUDE_SEARCHPATH)
SET(AQSIS_TIFF_LIBRARIES_SEARCHPATH)
SET(AQSIS_TIFF_LIBRARY_NAMES tiff)

IF(WIN32)
	IF(AQSIS_WIN32LIBS)
		SET(AQSIS_TIFF_INCLUDE_SEARCHPATH ${AQSIS_TIFF_INCLUDE_SEARCHPATH} ${AQSIS_WIN32LIBS}/libtiff/include)
		IF(MSVC AND MSVC80)
			SET(AQSIS_TIFF_LIBRARIES_SEARCHPATH ${AQSIS_TIFF_LIBRARIES_SEARCHPATH} ${AQSIS_WIN32LIBS}/libtiff/lib/vc8)
			SET(AQSIS_TIFF_LIBRARY_NAMES ${AQSIS_TIFF_LIBRARY_NAMES} libtiff)
		ENDIF(MSVC AND MSVC80)
	ENDIF(AQSIS_WIN32LIBS)
ENDIF(WIN32)

FIND_PATH(AQSIS_TIFF_INCLUDE_DIR
			tiff.h
			PATHS ${AQSIS_TIFF_INCLUDE_SEARCHPATH}
			DOC "Location of the libtiff headers"
			)

FIND_LIBRARY(AQSIS_TIFF_LIBRARIES
			NAMES ${AQSIS_TIFF_LIBRARY_NAMES}	
			PATHS ${AQSIS_TIFF_LIBRARIES_SEARCHPATH}
			DOC "Location of the libtiff library"
			)


STRING(COMPARE EQUAL "${AQSIS_TIFF_INCLUDE_DIR}" "AQSIS_TIFF_INCLUDE_DIR-NOTFOUND" AQSIS_TIFF_INCLUDE_DIR_NOTFOUND)
STRING(COMPARE EQUAL "${AQSIS_TIFF_LIBRARIES}" "AQSIS_TIFF_LIBRARIES-NOTFOUND" AQSIS_TIFF_LIBRARIES_NOTFOUND)

IF(NOT AQSIS_TIFF_LIBRARIES_NOTFOUND AND NOT AQSIS_TIFF_INCLUDE_DIR_NOTFOUND)
	SET(AQSIS_TIFF_FOUND 1)
ENDIF(NOT AQSIS_TIFF_LIBRARIES_NOTFOUND AND NOT AQSIS_TIFF_INCLUDE_DIR_NOTFOUND)

