SET(AQSIS_XSLTPROC_SEARCHPATH)
# If on win32, and the win32libs SVN module has been located, we can
# use the one in there.
IF(WIN32 AND AQSIS_WIN32LIBS)
	SET(AQSIS_XSLTPROC_SEARCHPATH ${AQSIS_WIN32LIBS}/GnuWin32/bin)
ENDIF(WIN32 AND AQSIS_WIN32LIBS)

FIND_PROGRAM(AQSIS_XSLTPROC_EXECUTABLE
	xsltproc
	PATHS ${AQSIS_XSLTPROC_SEARCHPATH}
	DOC "Location of the xsltproc executable"
)

STRING(COMPARE NOTEQUAL ${AQSIS_XSLTPROC_EXECUTABLE} "AQSIS_XSLTPROC_EXECUTABLE-NOTFOUND" AQSIS_XSLTPROC_EXECUTABLE_FOUND)
