FIND_PROGRAM(AQSIS_FLEX_EXECUTABLE
	flex
	DOC "Location of the flex executable"
)

STRING(COMPARE NOTEQUAL ${AQSIS_FLEX_EXECUTABLE} "AQSIS_FLEX_EXECUTABLE-NOTFOUND" AQSIS_FLEX_EXECUTABLE_FOUND)

FIND_PROGRAM(AQSIS_BISON_EXECUTABLE
	bison
	DOC "Location of the bison executable"
)

STRING(COMPARE NOTEQUAL ${AQSIS_BISON_EXECUTABLE} "AQSIS_BISON_EXECUTABLE-NOTFOUND" AQSIS_BISON_EXECUTABLE_FOUND)
