Import('env')
aqsltellenv = env.Copy()
aqsltellenv.AppendUnique(CPPPATH=['#/libslxargs'])
aqsltell_sources = Split("""
	aqsltell.cpp""")
aqsltell = aqsltellenv.Program('aqsltell', aqsltell_sources, LIBS=['argparse', 'shaderexecenv', 'shadervm', 'aqsistypes', 'slxargs'], LIBPATH=['$LIBDIR'])
aqsltellenv.Install('$BINDIR', aqsltell)
