Import('env')
Import('pixelsave')
gif2tif_sources=Split("""
	gif2tif.c""")

gif2tif = env.SharedLibrary('gif2tif', gif2tif_sources + pixelsave, LIBS=['$tiff_lib', '$z_lib'])

env.Install('$BINDIR', gif2tif)
