Import('env')
Import('pixelsave')
gif2tif_sources=Split("""
	gif2tif.c""")

# Set any platform specific options for this target
env.UseTargetOptions('plugin')
env.UseTargetOptions('texture_plugin')
env.UseTargetOptions('gif2tif')

gif2tif = env.SharedLibrary('gif2tif', gif2tif_sources + pixelsave, LIBS=['$tiff_lib', '$z_lib'])

env.Install('$BINDIR', gif2tif)
