Import('env')

d_exr_sources = Split("""
	d_exr.cpp
	""")

d_exr_headers =  Split("""
	dspyhlpr.h""")

if not env['no_exr']:
	d_exrenv = env.Copy()
	d_exrenv.AppendUnique(CPPPATH=['#/renderer/ddmanager'])
	d_exrenv.AppendUnique(CPPPATH=['$exr_include_path'])
	d_exrenv.AppendUnique(CPPDEFINES=['D_EXR_EXPORTS'])

	print(d_exrenv['LIBS'])


	# Set any platform specific target options.
	d_exrenv.UseTargetOptions('exr')

	exr = d_exrenv.SharedLibrary('d_exr', d_exr_sources)
	d_exrenv.Install('$DISPLAYSDIR', exr)

	Return('exr')

env.Distribute(d_exr_sources)
env.Distribute(d_exr_headers)
env.Distribute('dspyhlpr.c')
env.Distribute('tst.rib')
env.Distribute('exrtest.bat')
env.Distribute('SConscript')


