Import('env')
aqsltellenv = env.Copy()
aqsltellenv.AppendUnique(CPPPATH=['#/shadercompiler/slxargs'])
aqsltell_sources = Split("""
	aqsltell.cpp""")

aqsltellenv.AppendUnique(LIBS = ['argparse', 'slxargs', 'shadervm', 'aqsistypes'])

# Set any platform specific options for this target
aqsltellenv.UseTargetOptions('aqsltell')

aqsltell = aqsltellenv.Program('aqsltell', aqsltell_sources)

if env['MSVS_VERSION'] == '8.0':
	aqsltellenv.AddPostAction(aqsltell, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;1')
	
aqsltellenv.Install('$BINDIR', aqsltell)

env.Distribute(aqsltell_sources)
env.Distribute("SConscript")

