Import('env')
aqsltellenv = env.Copy()
aqsltellenv.AppendUnique(CPPPATH=['#/shadercompiler/slxargs'])
aqsltell_sources = Split("""
	aqsltell.cpp""")

aqsltellenv.AppendUnique(LIBS = ['argparse', 'slxargs', 'shadervm', 'shaderexecenv', 'aqsistypes'])

# Set any platform specific options for this target
aqsltellenv.UseTargetOptions('aqsltell')

aqsltell = aqsltellenv.Program('aqsltell', aqsltell_sources)
aqsltellenv.Install('$BINDIR', aqsltell)

env.Distribute('shadercompiler/aqsltell', aqsltell_sources)
env.Distribute('shadercompiler/aqsltell', "SConscript")

