import os

Import('env')

texlib_sources = Split("""
	mipmap.cpp
	tifffile.cpp
	tilearray.cpp
	""")

texlib_headers = Split("""
	itexfile.h
	mipmap.h
	texturetile.h
	tifffile.h
	tilearray.h
	""")

texlibenv = env.Copy()
texlibenv.AppendUnique(CPPPATH=['$tiff_include_path'])
texlibenv.Replace(LIBS = ['aqsistypes', '$tiff_lib', '$tiffxx_lib'])
texlibenv.UseTargetOptions('texlib')

texlib = texlibenv.SharedLibrary('aqsistex', [texlib_sources]);
texlibenv.PostBuildSharedLibrary(texlibenv, texlib)

texlibenv.InstallAs([os.path.join('${RENDERENGINEDIR}', '%s${SHLIB_VERSION_SUFFIX}') % (texlib[0],)], [texlib[0]])
texlibenv.PostInstallSharedLibrary(texlibenv, '${RENDERENGINEDIR}', texlib)

#-------------------------------------------------------------------------------
# Unit Tests

texlib_test_sources = Split('''
	mipmap_test.cpp
	tifffile_test.cpp
	''')

Import('testEnv')
testEnv = testEnv.Copy()
testEnv.AppendUnique(LIBS=['aqsistex', 'aqsistypes'])
testEnv.addUnitTest('texlib_test', texlib_test_sources)


env.Distribute(texlib_sources)
env.Distribute(texlib_test_sources)
env.Distribute(texlib_headers)
env.Distribute('SConscript')
